services:
  tika:
    container_name: tika
    image: apache/tika:latest
    restart: unless-stopped

    ports:
      - "9998:9998"

    volumes:
      - ../../runtime/tika/data:/data

    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo >/dev/tcp/localhost/9998' || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

    networks:
      - private-net

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  private-net:
    external: true
