services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "8080:80/tcp"

    volumes:
      - ../../runtime/adguardhome/work:/opt/adguardhome/work
      - ../../runtime/adguardhome/conf:/opt/adguardhome/conf

    networks:
      - private-net

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
        reservations:
          cpus: "0.5"
          memory: 250M

networks:
  private-net:
    external: true
