services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file:
      - ../../runtime/caddy/.env

    ports:
      - "80:80/tcp"
      - "443:443/tcp"

    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ../../runtime/caddy/data:/data
      - ../../runtime/caddy/config:/config

    networks:
      - private-net

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
        reservations:
          cpus: "0.5"
          memory: 250M

networks:
  private-net:
    external: true
